### ISSUE TITLE
ErrorException Trying to get property 'id' of non-object when editing category

### ISSUE THREAD

**Issue by Sell24** [LaravelDaily/Laravel-KnowledgeBase-FAQ#1]
I realize that this just a demo, and that you may not be supporting it but if you try and rename a category the code generates the above error in UpdateCategoryRequest.php on line 29.

                'required', 'unique:categories,slug,'.$this->route('article')->id

Fix is to change 'article' to category

**Comment by Marius-K** [comment]
@Sell24 thank you for the solution, solved!
