### ISSUE TITLE
Seeder gives an error at the ArticlesTableSeeder

### ISSUE THREAD

**Issue by emperorjm** [LaravelDaily/Laravel-KnowledgeBase-FAQ#7]
The following error is being thrown:

`Seeded:  CategoriesTableSeeder (0.17 seconds)
Seeding: TagsTableSeeder
Seeded:  TagsTableSeeder (0.51 seconds)
Seeding: ArticlesTableSeeder

   ErrorException  : implode(): Passing glue string after array is deprecated. Swap the parameters

  at /home/vagrant/knowledgebase/vendor/fzaninotto/faker/src/Faker/Provider/Lorem.php:95
    91| 
    92|         $words = static::words($nbWords);
    93|         $words[0] = ucwords($words[0]);
    94| 
  > 95|         return implode($words, ' ') . '.';
    96|     }
    97| 
    98|     /**
    99|      * Generate an array of sentences

  Exception trace:

  1   implode()
      /home/vagrant/knowledgebase/vendor/fzaninotto/faker/src/Faker/Provider/Lorem.php:95

  2   Faker\Provider\Lorem::sentence()
      /home/vagrant/knowledgebase/vendor/fzaninotto/faker/src/Faker/Generator.php:222

  Please use the argument -v to see more details.`

**Comment by Marius-K** [comment]
Hello @emperorjm 

Thank you for noticing this bug. To fix this issue, you need to update `fzaninotto/Faker` package. You can do it by running this line in console: `composer update fzaninotto/faker:^1.9.1`
